ARG IMAGE_BASE_TAG=latest
FROM harbor.elysiumstudios.se/elysium/nginx-game:${IMAGE_BASE_TAG}

ARG BUILD_GAME_NAME=NOTSET
ARG BUILD_GAME_VERSION=NOTSET
ENV GAME_NAME=${BUILD_GAME_NAME}
ENV GAME_VERSION=${BUILD_GAME_VERSION}

RUN mkdir -p ${NGINX_ROOT}/${BUILD_GAME_NAME}/${BUILD_GAME_VERSION}/
COPY / ${NGINX_ROOT}/${BUILD_GAME_NAME}/${BUILD_GAME_VERSION}/