namespace: elysium

image:
  repo: "harbor.elysiumstudios.se/elysium/"
  name: "fox-tale"

imagePullSecrets:
  - name: harborcred

containerSettings:
  name: http
  port: 80
  protocol: TCP

service:
  type: ClusterIP
  namePort: http
  port: 80
  targetPort: http

serviceaccount:
  create: true
  annotations: {}

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: dev.elysiumstudios.se
      paths:
        - path: /fox-tale
          pathType: Prefix
  tls: []

# probes:
#   liveness:
#     path: /fox-tale
#   readiness:
#     path: /fox-tale


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 128m
    memory: 256Mi

podAnnotations: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60