apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace | default "elysium" }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- include "service.elysiumLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "https" }}
      protocol: TCP
      name: {{ .Values.service.namePort | default "https" }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}